### PR TITLE
Revert "Flag to avoid creating subdirectories in output directory"

### PR DESCRIPTION
**Pull request by pedrorvc**
Reverts B-UMMI/chewBBACA#57

### CODE REVIEW

**Comment by cimendes** [comment]
LGTM. Feel free to merge! :+1:

**Comment by ramirma** [comment]
@TheBready, upon more careful testing we concluded that the change you propose, although potentially useful for some users, would create errors with frequently used options with the -o argument.
We will keep your suggestion in mind for a future update of chewBBACA.

**Comment by ramirma** [comment]
Still on this @TheBready, if you use `-o ./` this should result in a behavior similar to what you suggest (chewBBACA will not create an additional subdirectory for the results of that run)

**Comment by TheBready** [comment]
@ramirma  Yes, thanks that should work.

**Pull request merged**
