### PR TITLE
Fixes issue #6

### PR DESCRIPTION
**Pull request by andersgs**
It will be robust for versions 2.5 to 2.9. You may have to change the search pattern after that, but should not be too difficult.

Also, in Python 3.6, `subprocess.run` is introduced with lots of interesting things, which is designed to replace `subprocess.Popen`. It solves some of the awkwardness of Popen, and is the currently recommended way of making system calls. Check it out: https://docs.python.org/3.6/library/subprocess.html

Cheers. A.

### CODE REVIEW

**Comment by mickaelsilva** [comment]
I guess that the fix will last for a while now (I wasn't aware that there was a 2.7 blast version already).

There are some other `subprocess.Popen` on the code, calling prodigal for instance. I'll also change them considering `subprocess.run`.

Thanks for the valuable feedback @andersgs .

**Comment by mickaelsilva** [comment]
@andersgs we had a discussion here on the group and decided to change back the `subprocess.run` to `subprocess.Popen`. The reason is that with python <3.5 versions it would break and also from the documentation it seems the `run` was aimed at replacing older functions like for instance `call`.

**Comment by andersgs** [comment]
Hi @mickaelsilva. No worries, but then you need to do a bit more in order for the code to work:
```    proc = subprocess.Popen([BlastpPath, '-version'], stdout=subprocess.PIPE)
    stdout, stderr = proc.communicate()
    version_string = stdout.decode('utf8')
    blast_version_pat = re.compile(r'2.[5-9]')
    if not blast_version_pat.search(version_string):
		m = blast_version_pat.search(version_string).group()
        print ("your blast version is " + str(version_string))
        print ("update your blast to 2.5.0 or above, will exit program")
        sys.exit()
    else:
        print ("blast version is up to date, the program will continue")
```
Cheers. A.

**Comment by mickaelsilva** [comment]
@andersgs I forgot to change the decode part... thanks for the code! :)

**Pull request merged**
